GET http://localhost:3000/movies/
###

POST http://localhost:3000/movies/
Content-type: Application/json


{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###

PUT http://localhost:3000/movies/:movieId/
Content-type: Application/json 

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###


GET http://localhost:3000/movies/movies/:movieId/
###

DELETE http://localhost:3000/movies/movies/:movieId/
###


GET http://localhost:3000/directors/:directorId/movies/
###

GET http://localhost:3000/directors
###